version: "3"

services:
  namenode:
    image: nvtienanh/hadoop-namenode:${HADOOP_TAG}
    container_name: namenode
    hostname: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    ports:
      - 9870:9870
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net

  datanode:
    image: nvtienanh/hadoop-datanode:${HADOOP_TAG}
    container_name: datanode
    hostname: datanode
    volumes:
      - ./data/datanode:/hadoop/dfs/name
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - 9864:9864
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net
  
  resourcemanager:
    image: nvtienanh/hadoop-resourcemanager:${HADOOP_TAG}
    container_name: resourcemanager
    hostname: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    ports:
      - 8088:8088
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net

  nodemanager:
    image: nvtienanh/hadoop-nodemanager:${HADOOP_TAG}
    container_name: nodemanager
    hostname: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    ports:
      - 8042:8042
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net
  
  historyserver:
    image: nvtienanh/hadoop-historyserver:${HADOOP_TAG}
    container_name: historyserver
    hostname: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - ./data/historyserver:/hadoop/yarn/timeline
    ports:
      - 8188:8188
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net

networks:
  hadoop-net:
    external:
      name: hadoop-net
