version: "3"

services:
  hue:
    image: nvtienanh/hue:${HUE_TAG}
    hostname: hue
    container_name: hue
    networks:
      - hadoop-net
    environment:
      - NAMENODE_HOST=namenode
    ports:
     - "8888:8888"
    volumes:
      - ./pseudo-distributed.ini:/usr/share/hue/desktop/conf/pseudo-distributed.ini

  namenode:
    image: nvtienanh/hadoop-namenode:${HADOOP_TAG}
    hostname: namenode
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net

  datanode1:
    image: nvtienanh/hadoop-datanode:${HADOOP_TAG}
    hostname: datanode1
    container_name: datanode1
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net
  
  datanode2:
    image: nvtienanh/hadoop-datanode:${HADOOP_TAG}
    hostname: datanode2
    container_name: datanode2
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net
    
  historyserver:
    image: nvtienanh/hadoop-historyserver:${HADOOP_TAG}
    container_name: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864"
    volumes:
      - ./data/hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      - hadoop-net

networks:
  hadoop-net:
    external:
      name: hadoop-net

