version: "3"

services:
  hue:
    image: nvtienanh/hue:${HUE_TAG}
    hostname: hue
    container_name: hue
    networks:
      - hadoop-net
    environment:
      - NAMENODE_HOST=namenode
    ports:
     - "8888:8888"
    volumes:
      - ./hue.ini:/hue/desktop/conf/hue.ini
  
networks:
  hadoop-net:
    external:
      name: hadoop-net

